#!/usr/bin/env python3
"""Bundle index.html + css/style.css + js/game.js into one self-contained
standalone.html, so the game can be opened straight from a single file with
no server and no separate CSS/JS to fetch.

Run this after editing index.html, css/style.css, or js/game.js:

    python3 scripts/build_standalone.py
"""

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
INDEX = ROOT / "index.html"
STYLE = ROOT / "css" / "style.css"
GAME_JS = ROOT / "js" / "game.js"
OUTPUT = ROOT / "standalone.html"


def build():
    index_html = INDEX.read_text()
    style_css = STYLE.read_text()
    game_js = GAME_JS.read_text()

    # Inline the external stylesheet link as a <style> block.
    index_html = index_html.replace(
        '<link rel="stylesheet" href="css/style.css" />',
        f"<style>\n{style_css}\n</style>",
    )

    # Inline the game script in place of the external <script src>.
    index_html = re.sub(
        r'<script src="js/game\.js"></script>',
        f"<script>\n{game_js}\n</script>",
        index_html,
    )

    banner = (
        "<!--\n"
        "  This file is generated by scripts/build_standalone.py from index.html,\n"
        "  css/style.css, and js/game.js. Edit those files, not this one, then\n"
        "  re-run the script to regenerate it.\n"
        "-->\n"
    )
    OUTPUT.write_text(banner + index_html)
    print(f"Wrote {OUTPUT.relative_to(ROOT)} ({OUTPUT.stat().st_size:,} bytes)")


if __name__ == "__main__":
    build()
